@HOST=http://localhost:3000/
@TOKEN=dev
@DATABASE=daira

###CrearEtapa
POST {{HOST}}Proyectos/CrearEtapa HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "id_proyecto": 3,
    "nombre": " "
}

@IDETAPA = 4
###EliminarEtapa
DELETE  {{HOST}}Proyectos/EliminarEtapa/{{IDETAPA}} HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}


@IDPROYECTO = 3
###ObtenerEtapa
GET {{HOST}}Proyectos/ObtenerEtapas/{{IDPROYECTO}} HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ModificarEtapa
PUT {{HOST}}Proyectos/ModificarEtapa HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "id": 5,
    "id_proyecto": 3,
    "nombre": "Comprar herramientas",
    "estado": true
}