@HOST=http://localhost:3000/
@TOKEN=dev
@DATABASE=daira

###CrearEtapa
POST {{HOST}}Proyectos/CrearEtapa HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "ID_proyecto":12,
    "Nombre":"Etapa 2",
    "Prioridad":"ALTA"
}

###EliminarEtapa
DELETE  {{HOST}}Proyectos/EliminarEtapa/5 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ObtenerEtapa
GET {{HOST}}Proyectos/ObtenerEtapas HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ModificarEtapa
PUT {{HOST}}Proyectos/ModificarEtapa HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "id":9,
    "id_proyecto":13,
    "nombre":"Etapa 3",
    "prioridad":"MEDIA"
}