@HOST=http://localhost:3000/
@TOKEN=dev
@DATABASE=daira

###CrearProyecto
POST {{HOST}}Proyectos/CrearProyecto HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "Nombre":"Proyecto 4",
    "Prioridad":"ALTA",
    "Fecha_Inicio":"2023-06-20",
    "Fecha_Fin":"2023-07-20"
}

###EliminarProyecto
DELETE {{HOST}}Proyectos/EliminarProyecto/13 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ObtenerProyectos
GET {{HOST}}Proyectos/ObtenerProyectos HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ModificarProyecto
PUT {{HOST}}Proyectos/ModificarProyecto HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "Id":12,
    "Nombre":"Proyecto Modificado",
    "Prioridad": "MEDIA",
    "Fecha_inicio": "2023-06-22",
    "Fecha_fin": "2023-07-21"
}