@HOST=http://localhost:3000/
@TOKEN=dev
@DATABASE=daira

###CrearProyecto
POST {{HOST}}Proyectos/CrearProyecto HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "nombre":"Proyecto test",
    "prioridad":"ALTA",
    "fecha": "2023-11-12"
}

@IDPROYECTO = 6
###EliminarProyecto
DELETE {{HOST}}Proyectos/EliminarProyecto/{{IDPROYECTO}} HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ObtenerProyectos
GET {{HOST}}Proyectos/ObtenerProyectos HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ModificarProyecto
PUT {{HOST}}Proyectos/ModificarProyecto HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "id": 2,
    "nombre": "Pintar habitación",
    "prioridad": "MEDIA",
    "fecha": "2023-09-17"
}