@HOST=http://localhost:3000/
@TOKEN=dev
@DATABASE=daira

###CrearTarea
POST {{HOST}}Proyectos/CrearTarea HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "id_etapa":8,
    "Nombre":"",
    "Descripcion":"Esta es una tarea de prueba",
    "Plazo":5
}

###EliminarTarea
DELETE  {{HOST}}Proyectos/EliminarTarea/4 HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ObtenerTarea
GET {{HOST}}Proyectos/ObtenerTareas HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

###ModificarTarea
PUT {{HOST}}Proyectos/ModificarTarea HTTP/1.1
Content-Type: application/json
Authorization: {{TOKEN}}
Database: {{DATABASE}}

{
    "id":1,
    "id_etapa":3,
    "nombre":"",
    "descripcion":"nueva descripcion",
    "plazo":4
}